### ISSUE TITLE
Update the JWST sensitivity files

### ISSUE THREAD

**Issue by hrwakeford** [Exo-TiC/ExoTiC-LD#25]
Update the JWST sensitivity files in the zenodo data file with the on sky profiles.

**Comment by hrwakeford** [comment]
@DavoGrant please update the Zenodo links to 10.5281/zenodo.7871414 which has the new sensitivity files. 

The read the docs still points to your fork of the repository so that also needs to be fixed. These can then constitute an update in the Docs and a V3.1.0 release of the package

**Comment by hrwakeford** [comment]
@DavoGrant I made a mistake and forgot to add back in the HST, Spitzer & Tess throughputs so will need to do that in the morning and let you know

**Comment by hrwakeford** [comment]
Okay @DavoGrant this one is now correct v3.1.1 It is also in the right units and format as a bonus :p

md Zenodo badge: [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.7874667.svg)](https://doi.org/10.5281/zenodo.7874667)

URL: https://doi.org/10.5281/zenodo.7874667

**Comment by DavoGrant** [comment]
A handful of the sensitivity files have changed name slightly. The problem files are:

- JWST_NIRCam_F444_throughput.csv -- > JWST_NIRCam_F444W_throughput.csv
- JWST_NIRSpec_G140H-f070_throughput.csv -- > JWST_NIRSpec_G140H-f070lp_throughput.csv
- JWST_NIRSpec_G140H-f100_throughput.csv -- > JWST_NIRSpec_G140H-f100lp_throughput.csv
- JWST_NIRSpec_G140M-f070_throughput.csv -- > JWST_NIRSpec_G140M-f070lp_throughput.csv
- JWST_NIRSpec_G140M-f100_throughput.csv -- > JWST_NIRSpec_G140M-f100lp_throughput.csv

Can we reset the file names rather than change the code? This will avoid any issues with backwards compatibility.

**Comment by hrwakeford** [comment]
Done 
[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.7874921.svg)](https://doi.org/10.5281/zenodo.7874921)

https://zenodo.org/badge/DOI/10.5281/zenodo.7874921.svg

v3.1.2
